USE ENCANTO_ODONTO
GO
-- 1. TABELA ENDERECO (Com IDENTITY para auto incremento)
CREATE TABLE ENDERECO (
    ID_ENDERECO INT PRIMARY KEY IDENTITY(1,1),
    LOGRADOURO VARCHAR(255) NOT NULL,
    NUMERO INT,
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100),
    CEP CHAR(8)
);
GO

-- 2. TABELA ESPECIALIDADE
CREATE TABLE ESPECIALIDADE (
    ID_ESPECIALIDADE INT PRIMARY KEY IDENTITY(1,1),
    NOME_ESPECIALIDADE VARCHAR(100) UNIQUE NOT NULL
);
GO

-- 3. TABELA PROCEDIMENTO
CREATE TABLE PROCEDIMENTO (
    ID_PROCEDIMENTO INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(150) UNIQUE NOT NULL,
    VALOR_BASE DECIMAL(10, 2) NOT NULL,
    PERCENTUAL_COMISSAO DECIMAL(4, 2) NOT NULL
);
GO

-- 4. TABELA PRODUTO_ESTOQUE
CREATE TABLE PRODUTO_ESTOQUE (
    ID_PRODUTO INT PRIMARY KEY IDENTITY(1,1),
    NOME_PRODUTO VARCHAR(150) NOT NULL,
    QTD_ESTOQUE INT NOT NULL,
    CUSTO_UNITARIO DECIMAL(10, 2) NOT NULL
);
GO

-- ---
-- TABELAS DEPENDENTES (COM FKs)
-- ---

-- 5. TABELA PACIENTE
CREATE TABLE PACIENTE (
    ID_PACIENTE INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,
    CPF CHAR(11) UNIQUE NOT NULL,
    ID_ENDERECO INT,
    TELEFONE VARCHAR(20),
    HISTORICO_MEDICO VARCHAR(MAX), -- Tipo para texto longo no SQL Server
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
);
GO

-- 6. TABELA PROFISSIONAL
CREATE TABLE PROFISSIONAL (
    ID_PROFISSIONAL INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,
    CRO CHAR(20) UNIQUE NOT NULL,
    ID_ENDERECO INT,
    TELEFONE VARCHAR(20),
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
);
GO

-- 7. TABELA PROFISSIONAL_ESPECIALIDADE (Tabela Associativa N:M)
CREATE TABLE PROFISSIONAL_ESPECIALIDADE (
    ID_PROFISSIONAL INT,
    ID_ESPECIALIDADE INT,
    DATA_CERTIFICACAO DATE,
    PRIMARY KEY (ID_PROFISSIONAL, ID_ESPECIALIDADE),
    FOREIGN KEY (ID_PROFISSIONAL) REFERENCES PROFISSIONAL(ID_PROFISSIONAL),
    FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADE(ID_ESPECIALIDADE)
);
GO

-- 8. TABELA CONSUMO_PADRAO (Tabela Associativa N:M)
CREATE TABLE CONSUMO_PADRAO (
    ID_PROCEDIMENTO INT,
    ID_PRODUTO INT,
    QTD_PADRAO DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (ID_PROCEDIMENTO, ID_PRODUTO),
    FOREIGN KEY (ID_PROCEDIMENTO) REFERENCES PROCEDIMENTO(ID_PROCEDIMENTO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO_ESTOQUE(ID_PRODUTO)
);
GO


-- 9. TABELA CONSULTA
CREATE TABLE CONSULTA (
    ID_CONSULTA INT PRIMARY KEY IDENTITY(1,1),
    ID_PACIENTE INT NOT NULL,
    ID_PROFISSIONAL INT NOT NULL,
    DATA_HORA DATETIME NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    VALOR_TOTAL DECIMAL(10, 2) DEFAULT 0.00,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
    FOREIGN KEY (ID_PROFISSIONAL) REFERENCES PROFISSIONAL(ID_PROFISSIONAL)
);
GO


-- 10. TABELA ATENDIMENTO_PROCEDIMENTO
CREATE TABLE ATENDIMENTO_PROCEDIMENTO (
    ID_ATENDIMENTO_PROCEDIMENTO INT PRIMARY KEY IDENTITY(1,1),
    ID_CONSULTA INT NOT NULL,
    ID_PROCEDIMENTO INT NOT NULL,
    VALOR_COBRADO DECIMAL(10, 2) NOT NULL,
    VALOR_COMISSAO DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA(ID_CONSULTA),
    FOREIGN KEY (ID_PROCEDIMENTO) REFERENCES PROCEDIMENTO(ID_PROCEDIMENTO)
);
GO


-- 11. TABELA USO_MATERIAL
CREATE TABLE USO_MATERIAL (
    ID_USO_MATERIAL INT PRIMARY KEY IDENTITY(1,1),
    ID_ATENDIMENTO_PROCEDIMENTO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QTD_REAL_CONSUMIDA DECIMAL(10, 2) NOT NULL,
    CUSTO_TOTAL_MATERIAL DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_ATENDIMENTO_PROCEDIMENTO) REFERENCES ATENDIMENTO_PROCEDIMENTO(ID_ATENDIMENTO_PROCEDIMENTO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO_ESTOQUE(ID_PRODUTO)
);
GO


-- 12. TABELA PAGAMENTO_PACIENTE
CREATE TABLE PAGAMENTO_PACIENTE (
    ID_PAGAMENTO INT PRIMARY KEY IDENTITY(1,1),
    ID_CONSULTA INT NOT NULL,
    FORMA_PAGAMENTO VARCHAR(50) NOT NULL,
    DATA_PAGAMENTO DATETIME NOT NULL,
    VALOR_PAGO DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA(ID_CONSULTA)
);
GO

