USE ENCANTO_ODONTO;
GO

-- INÍCIO DA TRANSAÇÃO: Tudo que for executado entre BEGIN e COMMIT/ROLLBACK
-- pode ser desfeito.
BEGIN TRANSACTION;

-- DELETE: Remover Pacientes 'Fantasmas' (Sem consultas)
DELETE FROM PACIENTE
WHERE ID_PACIENTE NOT IN (
    SELECT ID_PACIENTE FROM CONSULTA
);

SELECT * FROM PACIENTE 
WHERE ID_PACIENTE NOT IN(
    SELECT ID_PACIENTE FROM CONSULTA); -- VERIFICANDO SE O DELETE FUNCIONA

ROLLBACK TRANSACTION; 

-- Se você quisesse salvar as alterações: 
-- COMMIT TRANSACTION;
GO

SELECT * FROM PACIENTE 
WHERE ID_PACIENTE NOT IN(
    SELECT ID_PACIENTE FROM CONSULTA); -- VERIFICANDO SE O ROLLBACK FUNCIONA