-- INSERÇÃO OTIMIZADA USANDO JOIN E CÁLCULO DE CUSTO
INSERT INTO USO_MATERIAL (ID_ATENDIMENTO_PROCEDIMENTO, ID_PRODUTO, QTD_REAL_CONSUMIDA, CUSTO_TOTAL_MATERIAL)
SELECT 
    AP.ID_ATENDIMENTO_PROCEDIMENTO,
    CP.ID_PRODUTO,
    -- QTD_REAL_CONSUMIDA é a QTD_PADRAO
    CP.QTD_PADRAO,
    -- CUSTO_TOTAL_MATERIAL é o CUSTO_UNITARIO do produto multiplicado pela QTD_PADRAO
    PE.CUSTO_UNITARIO * CP.QTD_PADRAO
FROM 
    ATENDIMENTO_PROCEDIMENTO AP
-- 1. JOIN com Consumo Padrão para saber quais produtos estão associados a esse procedimento
INNER JOIN 
    CONSUMO_PADRAO CP ON AP.ID_PROCEDIMENTO = CP.ID_PROCEDIMENTO
-- 2. JOIN com Produto Estoque para obter o CUSTO_UNITARIO
INNER JOIN 
    PRODUTO_ESTOQUE PE ON CP.ID_PRODUTO = PE.ID_PRODUTO
ORDER BY 
    AP.ID_ATENDIMENTO_PROCEDIMENTO;
GO

SELECT 'STATUS: População da tabela USO_MATERIAL concluída com sucesso. Total de Registros: ' + CAST(COUNT(*) AS VARCHAR)
FROM USO_MATERIAL;
GO