-- POPULAÇÃO DA TABELA ESPECIALIDADE
INSERT INTO ESPECIALIDADE (NOME_ESPECIALIDADE) VALUES
('ESTÉTICA DENTAL'), --
('IMPLANTODONTIA'),
('ORTODONTIA'),
('HARMONIZAÇÃO OROFACIAL'),
('CLÍNICA GERAL'),
('PERIODONTIA'),
('ENDODONTIA'),
('CIRURGIA ORAL');
GO

SELECT * FROM ESPECIALIDADE;