-- POPULANDO A TABELA PAGAMENTO_PACIENTE ULTIMA TABELA A SER POPULADA PARA MANTER A INTEGRIDADE DO BANCO
-- INSERÇÃO OTIMIZADA USANDO INSERT...SELECT
INSERT INTO PAGAMENTO_PACIENTE (ID_CONSULTA, DATA_PAGAMENTO, VALOR_PAGO, FORMA_PAGAMENTO)
SELECT
    C.ID_CONSULTA,
    -- Data de Pagamento: Aleatória entre a Data da Consulta e 5 dias depois
    DATEADD(DAY, CAST(ABS(CHECKSUM(NEWID())) % 5 AS INT), C.DATA_HORA) AS DATA_PAGAMENTO,
    C.VALOR_TOTAL AS VALOR_PAGO,
    -- Forma de Pagamento aleatória
    CASE CAST(ABS(CHECKSUM(NEWID())) % 4 AS INT)
        WHEN 0 THEN 'CARTAO_CREDITO'
        WHEN 1 THEN 'DEBITO'
        WHEN 2 THEN 'PIX'
        ELSE 'DINHEIRO'
    END AS FORMA_PAGAMENTO
FROM 
    CONSULTA C
WHERE 
    C.STATUS = 'REALIZADA' AND C.VALOR_TOTAL > 0; -- Apenas consultas realizadas e cobradas
GO

SELECT 'STATUS: População da tabela PAGAMENTO_PACIENTE concluída com sucesso. Total de Registros: ' + CAST(COUNT(*) AS VARCHAR)
FROM PAGAMENTO_PACIENTE;
GO