-- ATUALIZAÇÃO DO VALOR_TOTAL NA TABELA CONSULTA
UPDATE C
SET C.VALOR_TOTAL = (
    -- Soma o VALOR_COBRADO de todos os procedimentos relacionados
    SELECT SUM(AP.VALOR_COBRADO)
    FROM ATENDIMENTO_PROCEDIMENTO AP
    WHERE AP.ID_CONSULTA = C.ID_CONSULTA
)
FROM CONSULTA C
WHERE C.STATUS = 'REALIZADA'

-- Trata consultas realizadas sem procedimento (deixa o valor zerado)
UPDATE CONSULTA
SET VALOR_TOTAL = 0.00
WHERE VALOR_TOTAL IS NULL AND STATUS = 'REALIZADA';

GO

SELECT TOP 10 ID_CONSULTA, STATUS, VALOR_TOTAL FROM CONSULTA WHERE STATUS = 'REALIZADA' ORDER BY ID_CONSULTA;