USE ENCANTO_ODONTO;
GO

-- INÍCIO DA TRANSAÇÃO: Tudo que for executado entre BEGIN e COMMIT/ROLLBACK
-- pode ser desfeito.
BEGIN TRANSACTION;

-- UPDATE: Repor Estoque Crítico (Onde a QTD_ESTOQUE é baixa)
-- Adiciona 500 unidades para produtos abaixo de 100 unidades.
UPDATE PRODUTO_ESTOQUE
SET 
    QTD_ESTOQUE = QTD_ESTOQUE + 500 
WHERE 
    QTD_ESTOQUE < 100;

SELECT * FROM PRODUTO_ESTOQUE WHERE QTD_ESTOQUE < 100; -- VERIFICANDO SE O UPDATE SURTIU EFEITO

ROLLBACK TRANSACTION; 

-- Se você quisesse salvar as alterações: 
-- COMMIT TRANSACTION;
GO

SELECT * FROM PRODUTO_ESTOQUE WHERE QTD_ESTOQUE < 100; -- COMPROVANDO QUE O ROLLBACK FUNCIONA
