USE ENCANTO_ODONTO;
GO

-- UPDATES PARA FORÇAR A TER UMA RECEITA MAIS BAIXA.
-- Força o ID 1 a ter um desempenho muito baixo (redução de 90%).
UPDATE AP
SET 
    VALOR_COBRADO = VALOR_COBRADO * 0.10, 
    VALOR_COMISSAO = VALOR_COMISSAO * 0.10
FROM 
    ATENDIMENTO_PROCEDIMENTO AP
JOIN 
    CONSULTA C ON AP.ID_CONSULTA = C.ID_CONSULTA
WHERE 
    C.ID_PROFISSIONAL = 1;

-- Força o ID 2 a ter um desempenho mediano (redução de 80%).
UPDATE AP
SET 
    VALOR_COBRADO = VALOR_COBRADO * 0.20, 
    VALOR_COMISSAO = VALOR_COMISSAO * 0.20
FROM 
    ATENDIMENTO_PROCEDIMENTO AP
JOIN 
    CONSULTA C ON AP.ID_CONSULTA = C.ID_CONSULTA
WHERE 
    C.ID_PROFISSIONAL = 2;

-- 3. Perfil de ALTO VOLUME / BAIXA MARGEM 
-- Comissão BAIXA, mas Margem ALTA (ou vice-versa). 
-- Força o ID 3 a ter Margem Alta, mas Comissão Zero 
UPDATE AP
SET 
    VALOR_COMISSAO = 0.00
FROM 
    ATENDIMENTO_PROCEDIMENTO AP
JOIN 
    CONSULTA C ON AP.ID_CONSULTA = C.ID_CONSULTA
WHERE 
    C.ID_PROFISSIONAL = 3;

GO

-- 4. Re-calcula o VALOR_TOTAL na CONSULTA (ESSENCIAL)
-- Este UPDATE deve ser executado SEMPRE após a manipulação de VALOR_COBRADO.
UPDATE C
SET C.VALOR_TOTAL = (SELECT SUM(AP.VALOR_COBRADO) FROM ATENDIMENTO_PROCEDIMENTO AP WHERE AP.ID_CONSULTA = C.ID_CONSULTA)
FROM CONSULTA C
WHERE C.STATUS = 'REALIZADA';

GO

USE ENCANTO_ODONTO;
GO
-- ROLLBACK
-- *** 1. UPDATE para tentar REVERTER o VALOR_COBRADO e VALOR_COMISSAO ***
-- Este comando presume que você não tem outros UPDATEs que mudaram a relação original.
-- Ele tenta reverter a Receita e a Comissão para o VALOR_BASE do Procedimento.
UPDATE AP
SET 
    AP.VALOR_COBRADO = P.VALOR_BASE,
    AP.VALOR_COMISSAO = P.VALOR_BASE * (P.PERCENTUAL_COMISSAO / 100.00)
FROM 
    ATENDIMENTO_PROCEDIMENTO AP
JOIN 
    PROCEDIMENTO P ON AP.ID_PROCEDIMENTO = P.ID_PROCEDIMENTO
WHERE 
    AP.VALOR_COBRADO <> P.VALOR_BASE; -- Apenas atualiza o que foi alterado

GO

-- *** 2. Re-calcula o VALOR_TOTAL na CONSULTA ***
-- ESSENCIAL após qualquer mudança nos valores cobrados.
UPDATE C
SET C.VALOR_TOTAL = (SELECT SUM(AP.VALOR_COBRADO) FROM ATENDIMENTO_PROCEDIMENTO AP WHERE AP.ID_CONSULTA = C.ID_CONSULTA)
FROM CONSULTA C
WHERE C.STATUS = 'REALIZADA';