USE ENCANTO_ODONTO;
GO

-- 1. Restaura o VALOR_COMISSAO para o ID_PROFISSIONAL = 3 (DRA. CAMILA GOMES)
UPDATE AP
SET 
    -- VALOR_COMISSAO = VALOR_COBRADO * (PERCENTUAL_COMISSAO / 100.00)
    AP.VALOR_COMISSAO = AP.VALOR_COBRADO * (P.PERCENTUAL_COMISSAO / 100.00)
FROM 
    ATENDIMENTO_PROCEDIMENTO AP
JOIN 
    CONSULTA C ON AP.ID_CONSULTA = C.ID_CONSULTA
JOIN
    PROCEDIMENTO P ON AP.ID_PROCEDIMENTO = P.ID_PROCEDIMENTO
WHERE 
    C.ID_PROFISSIONAL = 3; -- Apenas para a Dra. Camila Gomes

GO

-- 2. Confirmação (Verificação na View)
SELECT * FROM RELATORIO_COMISSAO_CUSTO
WHERE ID_PROFISSIONAL = 3;
GO