USE ENCANTO_ODONTO;
GO

IF OBJECT_ID('RELATORIO_FLUXO_PAGAMENTO') IS NOT NULL
    DROP VIEW RELATORIO_FLUXO_PAGAMENTO;
GO

-- VIEW 5: Fluxo de Pagamento Realizado (LIMPA)
CREATE VIEW RELATORIO_FLUXO_PAGAMENTO AS
SELECT
    FORMA_PAGAMENTO,
    SUM(VALOR_PAGO) AS Valor_Total_Pago,
    COUNT(ID_PAGAMENTO) AS Total_Transacoes
FROM
    PAGAMENTO_PACIENTE
GROUP BY
    FORMA_PAGAMENTO;

GO

-- Teste da View
SELECT * FROM RELATORIO_FLUXO_PAGAMENTO
ORDER BY Valor_Total_Pago DESC;
GO