USE [ENCANTO_ODONTO]
GO

/****** Object:  View [dbo].[RELATORIO_COMISSAO_CUSTO]    Script Date: 13/11/2025 14:26:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- VIEW 1: Receita vs. Despesa por Profissional
CREATE VIEW [dbo].[RELATORIO_COMISSAO_CUSTO] AS
WITH 
ReceitaComissao AS (
    SELECT
        P.ID_PROFISSIONAL,
        SUM(AP.VALOR_COBRADO) AS Total_Receita_Bruta,
        SUM(AP.VALOR_COMISSAO) AS Total_Comissao
    FROM
        PROFISSIONAL P
    JOIN CONSULTA C ON P.ID_PROFISSIONAL = C.ID_PROFISSIONAL
    JOIN ATENDIMENTO_PROCEDIMENTO AP ON C.ID_CONSULTA = AP.ID_CONSULTA
    GROUP BY P.ID_PROFISSIONAL
),
CustoMaterial AS (
    SELECT
        P.ID_PROFISSIONAL,
        SUM(UM.CUSTO_TOTAL_MATERIAL) AS Total_Custo
    FROM
        PROFISSIONAL P
    JOIN CONSULTA C ON P.ID_PROFISSIONAL = C.ID_PROFISSIONAL
    JOIN ATENDIMENTO_PROCEDIMENTO AP ON C.ID_CONSULTA = AP.ID_CONSULTA
    JOIN USO_MATERIAL UM ON AP.ID_ATENDIMENTO_PROCEDIMENTO = UM.ID_ATENDIMENTO_PROCEDIMENTO
    GROUP BY P.ID_PROFISSIONAL
)

SELECT
    P.ID_PROFISSIONAL,
    P.NOME AS Nome_Profissional,
    COALESCE(RC.Total_Comissao, 0) AS Total_Comissao_Gerada,
    COALESCE(CM.Total_Custo, 0) AS Custo_Total_Materiais,
    COALESCE(RC.Total_Receita_Bruta, 0) AS Receita_Bruta_Gerada
FROM
    PROFISSIONAL P
LEFT JOIN ReceitaComissao RC ON P.ID_PROFISSIONAL = RC.ID_PROFISSIONAL
LEFT JOIN CustoMaterial CM ON P.ID_PROFISSIONAL = CM.ID_PROFISSIONAL;

GO


