USE ENCANTO_ODONTO;
GO
-- VIEW PARA VERIFICAR O HISTORICO DO PACIENTE COMPLETO
-- 1. DROP VIEW 
IF OBJECT_ID('HISTORICO_FINANCEIRO_PACIENTE') IS NOT NULL
    DROP VIEW HISTORICO_FINANCEIRO_PACIENTE;
GO

-- 2. CREATE VIEW 
CREATE VIEW HISTORICO_FINANCEIRO_PACIENTE AS
SELECT
    PA.ID_PACIENTE,
    PA.NOME AS Nome_Paciente,
    PA.CPF AS CPF_Paciente,
    EN.CIDADE AS Cidade_Paciente,
    C.ID_CONSULTA,
    C.DATA_HORA AS Data_Consulta,
    PR.NOME AS Procedimento_Realizado,
    AP.VALOR_COBRADO AS Valor_Cobrado_Procedimento,
    PP.FORMA_PAGAMENTO AS Forma_Pagamento
FROM
    PACIENTE PA
JOIN
    ENDERECO EN ON PA.ID_ENDERECO = EN.ID_ENDERECO
JOIN
    CONSULTA C ON PA.ID_PACIENTE = C.ID_PACIENTE
JOIN
    ATENDIMENTO_PROCEDIMENTO AP ON C.ID_CONSULTA = AP.ID_CONSULTA
JOIN
    PROCEDIMENTO PR ON AP.ID_PROCEDIMENTO = PR.ID_PROCEDIMENTO
LEFT JOIN 
    PAGAMENTO_PACIENTE PP ON C.ID_CONSULTA = PP.ID_CONSULTA
WHERE
    C.STATUS = 'REALIZADA';


GO

-- 3. Teste da View 
SELECT TOP 100 * FROM HISTORICO_FINANCEIRO_PACIENTE WHERE Cidade_Paciente = 'SAO PAULO'
ORDER BY Data_Consulta DESC; 
GO

-- Esta View fornece uma linha para cada procedimento realizado (e cobrado), associada ao paciente e à forma de pagamento da consulta correspondente.