USE ENCANTO_ODONTO;
GO

-- 1. DROP VIEW
IF OBJECT_ID('RELATORIO_RECEITA_PRODUTO') IS NOT NULL
    DROP VIEW RELATORIO_RECEITA_PRODUTO;
GO

-- 2. CREATE VIEW
CREATE VIEW RELATORIO_RECEITA_PRODUTO AS
SELECT
    PE.ID_PRODUTO,
    PE.NOME_PRODUTO AS Nome_Produto,
    PE.CUSTO_UNITARIO,
    SUM(UM.CUSTO_TOTAL_MATERIAL) AS Custo_Total_Consumido,
    
    -- Calcula a Receita gerada pelo produto (através do procedimento)
    SUM(AP.VALOR_COBRADO) AS Receita_Bruta_Associada,
    
    -- Margem de Contribuição por Produto (Receita Associada - Custo Consumido)
    (SUM(AP.VALOR_COBRADO) - SUM(UM.CUSTO_TOTAL_MATERIAL)) AS Margem_Contribuicao_Produto,
    
    COUNT(UM.ID_USO_MATERIAL) AS Qtd_Uso
FROM
    PRODUTO_ESTOQUE PE
JOIN
    USO_MATERIAL UM ON PE.ID_PRODUTO = UM.ID_PRODUTO
JOIN
    ATENDIMENTO_PROCEDIMENTO AP ON UM.ID_ATENDIMENTO_PROCEDIMENTO = AP.ID_ATENDIMENTO_PROCEDIMENTO
GROUP BY
    PE.ID_PRODUTO, PE.NOME_PRODUTO, PE.CUSTO_UNITARIO;

GO

-- 3. Teste da View
SELECT TOP 10 * FROM RELATORIO_RECEITA_PRODUTO
ORDER BY Margem_Contribuicao_Produto DESC;
GO