USE ENCANTO_ODONTO;
GO

-- 1. DROP VIEW
IF OBJECT_ID('PRODUTIVIDADE_ESPECIALIDADE') IS NOT NULL
    DROP VIEW PRODUTIVIDADE_ESPECIALIDADE;
GO

-- 2. CREATE VIEW
CREATE VIEW PRODUTIVIDADE_ESPECIALIDADE AS
SELECT
    E.NOME_ESPECIALIDADE AS Especialidade,
    COUNT(AP.ID_ATENDIMENTO_PROCEDIMENTO) AS Total_Procedimentos,
    SUM(AP.VALOR_COBRADO) AS Receita_Bruta_Total,
    AVG(AP.VALOR_COBRADO) AS Receita_Media_Procedimento,
    
    -- Para calcular o custo médio, precisamos do custo do material, 
    -- que é mais complexo devido ao relacionamento, vamos focar na Receita/Comissão
    AVG(AP.VALOR_COMISSAO) AS Comissao_Media_Procedimento
    
FROM
    ESPECIALIDADE E
JOIN
    PROFISSIONAL_ESPECIALIDADE PE ON E.ID_ESPECIALIDADE = PE.ID_ESPECIALIDADE
JOIN
    PROFISSIONAL P ON PE.ID_PROFISSIONAL = P.ID_PROFISSIONAL
JOIN
    CONSULTA C ON P.ID_PROFISSIONAL = C.ID_PROFISSIONAL
JOIN
    ATENDIMENTO_PROCEDIMENTO AP ON C.ID_CONSULTA = AP.ID_CONSULTA
WHERE
    C.STATUS = 'REALIZADA'
GROUP BY
    E.NOME_ESPECIALIDADE;

GO

-- 3. Teste da View
SELECT * FROM PRODUTIVIDADE_ESPECIALIDADE
ORDER BY Total_Procedimentos DESC;
GO